# Generated by Django 4.1.2 on 2022-10-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fecha_de_nacimiento',
            new_name='fecha_de_creacion',
        ),
    ]
